name: "Linting"

on:
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
          cache: true


      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
